### ISSUE TITLE
Update to wrangling section on project info page.

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/hca-tuatara#3]
We propose the following changes to the wrangling section on the project info page. 

**Page**:project info 
1. Capitalize  “W” in the title of this section (aesthetics) 
 
2. Update terminology in the "wrangling status" Change starting to "status"
3. Change "Effort" to "Project Source"  This field need source enums, for example, pre-publication, GEO, ENA. 

4. Remove the following fields:  “contacts”, “files”
5. first/last contact dates is not helpful. A most recent contact date seems to be the best solution.
6. Move “responders” up, and only keep First and last respond dates

**Comment by pnejad** [comment]
> 2. Update terminology in the "wrangling status" Change starting to ""

@cjvillar  what did you mean by this?

**Comment by JimKent** [comment]
Looks good overall.  On #4,  I cut respondents already which I think addressed the contact part.  The files part is sounds like it would be more useful to have URL of a brokering drive instead.

**Comment by JimKent** [comment]
#1 is done, with the first letter of all sections including "Wrangling" now capitalized.
#2 What do you want changed?  "status" as a status makes no sense.  Do you want something else instead of "starting" for the initial one?
#3 Renamed the field "Effort" to "Project Source".  The values here are controlled by the "x Project Source Type" table which currently can only be edited by Clay and me.   We'll add an ENA (or other Euro) import if EBI agrees to do it,  and we'll use their terms.  Perhaps they will want to import from the Expression Atlas as well as ENA, I don't know.
#4 - Files is gone.  In it's place is a slot for the URL to the wrangler drive.  While I was tinkering I moved the git ticket url to be inside the wrangling section next to the wrangler drive.  To me at least this makes sense, but perhaps other people than wranglers chat?
#5 - Could you just reframe "last contact" in your mind to not necessarily mean "final contact."  I prefer to keep it as "last" because it is shorter, and it avoids changes to code and database.
#6 - Ended up keeping contacts and ditching responders since we didn't need both and contacts is more familiar.

**Comment by JimKent** [comment]
ps - changes are currently just on the developers branch.   I'll bundle them together with some changes from other tickets and likely update the production instance later today.
