### ISSUE TITLE
Search Filter feedback

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/hca-tuatara#6]
Change "Effort" to “source”: GEO, pre-publication, ENA ... etc 
Change Assay techs to "library prep method"
ADD ‘organ’
ADD ‘disease’

**Comment by JimKent** [comment]
Ok.  Did this.  Disease has so many values it is making me want facets....

**Comment by pnejad** [comment]
@JimKent  Are we capturing disease at the donor or specimen level?

I think we should keep the two separate, or only capture specimen level disease.

For the tonsil dataset, the patients underwent a tonsillectomy due to obstructive sleep apnea. At the donor level, disease = obstructive sleep apnea. Specimen level, disease = healthy/normal.
